[workspace]
members = [
  # libraries
  "common",
  "providers",
  "strategies",
  # binaries
  "signal_backtester",
  "candle_scraper",
  #"options_scraper", # TODO: implement
  "quote_scraper",
  "signal_scraper",
  "historical_candle_scraper"
]
