[workspace]
members = [
  # libraries
  "common",
  "providers",
  "strategies",
  # binaries
  "backtester",
  "signal_backtester",
  "candle_scraper",
  "options_scraper",
  "quote_scraper",
  "signal_scraper"
]
